### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by mofodox** [tomichj/authenticate#7]
I can't seem to receive a reset password email even though I've changed the config file. Is there any tutorial on how to set that up?

**Comment by tomichj** [comment]
Authenticate uses ActionMailer, the email infrastructure included with Rails. Configuring ActionMailer is complex and environment-dependent.

The ActionMail basics are documented here:
https://guides.rubyonrails.org/action_mailer_basics.html

Sorry I can't be of more help.
